name: Deploy to Vercel via Hook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy Hook
        run: |
          HOOK_URL="https://api.vercel.com/v1/integrations/deploy/prj_kSlu24GWZ1U3kUFd0hUWnJo3KipL/jw4zUasX8K"
          echo "Calling Vercel Deploy Hook..."
          curl -s -X POST "$HOOK_URL" -o /tmp/resp.json -w "HTTP_STATUS:%{http_code}\n"
          echo "Response:" && cat /tmp/resp.json || true
        shell: bash

